runtime: python37
# https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices
# entrypoint: gunicorn -b :8080 -w 1 main:app
service: ecommerce
# api_version: 1
# threadsafe: yes
env: standard
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.9
  min_instances: 1
  max_instances: 1

handlers:
  - url: /static
    static_dir: static/
    secure: always
  - url: .*
    script: auto
    secure: always

includes:
  - env.yaml
# yarn build && python manage.py collectstatic && gcloud app deploy
