runtime: python37
service: ecommerce
# api_version: 1
# threadsafe: yes
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1

handlers:
  - url: /static
    static_dir: static/
    secure: always
  - url: .*
    script: auto
    secure: always

includes:
  - env.yaml
# python manage.py collectstatic && gcloud app deploy
